from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field


class SavedValuation(BaseModel):
    """
    Model for saved vehicle valuations.
    Maps to the public.saved_valuations table in Supabase.
    """
    
    # Primary key - auto-generated UUID by Supabase
    id: Optional[str] = Field(default=None, description="UUID generated by Supabase")
    
    # Foreign key to auth.users (enforced by RLS policies)
    user_id: str = Field(..., description="UUID of the user who saved this valuation")
    
    # User-provided title for the saved valuation
    title: str = Field(..., min_length=1, description="User-provided title/name for this valuation")
    
    # Parsed car details (stored as JSONB in Supabase)
    parsed_car: Dict[str, Any] = Field(
        ..., 
        description="Parsed vehicle details (year, manufacturer, model, odometer, etc.)"
    )
    
    # Valuation result (stored as JSONB in Supabase)
    valuation_result: Dict[str, Any] = Field(
        ..., 
        description="Valuation result including fair_price, price_range, explanation, confidence"
    )
    
    # Timestamps (managed by Supabase)
    created_at: Optional[datetime] = Field(default=None, description="When the valuation was saved")
    updated_at: Optional[datetime] = Field(default=None, description="Last time the valuation was updated")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat() if v else None
        }
    
    @property
    def fair_price(self) -> Optional[float]:
        """Convenience property to get the fair price from valuation_result"""
        return self.valuation_result.get('fair_price')
    
    @property
    def price_range(self) -> tuple:
        """Convenience property to get price range as (low, high) tuple"""
        low = self.valuation_result.get('price_range_low', 0)
        high = self.valuation_result.get('price_range_high', 0)
        return (low, high)
    
    @property
    def confidence(self) -> Optional[str]:
        """Convenience property to get confidence level"""
        return self.valuation_result.get('confidence')
    
    @property
    def vehicle_description(self) -> str:
        """Generate a brief vehicle description from parsed_car"""
        car = self.parsed_car
        year = car.get('year', '')
        make = car.get('manufacturer', '')
        model = car.get('model', '')
        return f"{year} {make} {model}".strip()
